### PR TITLE
fix(anthropic): remove `top_p` parameter for Claude 4.5 models

### LINKED ISSUE #520: [Bug]: `temperature` and `top_p` cannot both be specified for Claude Haiku 4.5 and Sonnet 4.5
### Opencommit Version

3.2.10

### Node Version

22.18.0

### NPM Version

10.9.3

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

*(Linux distro: NixOS)*

i set my OCO_MODEL to `claude-haiku-4-5` with the `anthropic` provider, and i get the following message when i run `oco`:

```
┌  opencommit
│
◓  Generating commit message   
│
└  ✖ 400 {"type":"error","error":{"type":"invalid_request_error","message":"`temperature` and `top_p` cannot both be specified for this model. Please use only one."},"request_id":"req_011CUK6BqmnBWwnEtihUBmak"}

│
└  ✖ Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"`temperature` and `top_p` cannot both be specified for this model. Please use only one."},"request_id":"req_011CUK6BqmnBWwnEtihUBmak"}
```

### Expected Behavior

opencommit should only set one of `temperature` or `top_p` for Claude models that don't support both, and it should successfully generate a commit message

### Current Behavior

opencommit cannot generate commit messages with Haiku 4.5 because Anthropic doesn't allow both `temperature` and `top_p` parameters to be set

### Possible Solution

remove either `temperature` or `top_p` from the parameters object when sending requests to Anthropic, optionally *only* for Haiku 4.5 (and other models with this issue, if applicable)

### Steps to Reproduce

1. set `OCO_MODEL=claude-haiku-4-5`
1. and `OCO_AI_PROVIDER=anthropic`
1. run `oco` or `git commit` after `oco hook set`

### Relevant log output

```shell
┌  opencommit
│
◓  Generating commit message   
│
└  ✖ 400 {"type":"error","error":{"type":"invalid_request_error","message":"`temperature` and `top_p` cannot both be specified for this model. Please use only one."},"request_id":"req_011CUK6BqmnBWwnEtihUBmak"}

│
└  ✖ Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"`temperature` and `top_p` cannot both be specified for this model. Please use only one."},"request_id":"req_011CUK6BqmnBWwnEtihUBmak"}
```

### PR DESCRIPTION
**Pull request by muni-corn**
removes the `top_p` parameter if the configured model string contains `-4-5`. this fixes #520 , where opencommit will fail because Anthropic does not support *both* `temperature` and `top_p` for their 4.5 models.

### CODE REVIEW

File: src/engine/anthropic.ts [hunk 1]
```diff
@@ -37,9 +37,14 @@ export class AnthropicEngine implements AiEngine {
       system: systemMessage,
       messages: restMessages,
       temperature: 0,
-      top_p: 0.1,
       max_tokens: this.config.maxTokensOutput
     };
+
+    // add top_p for non-4.5 models
+    if (!params.model.includes('-4-5')) {
```
Comment (di-sukharev) [inline src/engine/anthropic.ts]: we should add "claude" too, because another models can be called `4-5`, maybe deepseek come out in 4-5 version :)

**Review by di-sukharev — CHANGES_REQUESTED** [review]

**Comment by devacc00** [comment]
@di-sukharev ping

**Comment by Thevetat** [comment]
Anything here? Just had a fail from haiku 3.5 deprecation so now cant use this.
